title: Marisol Wickham Digital Portfolio
description: My name is Marisol Wickham. I am a senior at Charlotte Latin School. This year I will be documenting my work with Pearl (Atrium Rehab Facility) while a group and I work on medical assistive technology to help the patients. 

google_analytics:
theme: jekyll-theme-architect
